services:
  cosmosdb-nosql:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    restart: always
    ports:
      - "8081:8081"
      - "1234:1234"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:0a47e12e3693483cef5c71f35468b91d751611f172d2f97414e9c69113b106d9 # 3.34.0
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: azurite --location /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    volumes:
      - azurite:/data

volumes:
  azurite:
