[project]
name = "python-architecture"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.11.18",
    "azure-cosmos==4.9.0",
    "common",
    "domain",
    "fastapi[standard]==0.115.12",
    "poethepoet==0.34.0",
    "pydantic==2.11.4",
    "pydantic-settings[azure-key-vault]==2.9.1",
]

[dependency-groups]
dev = [
    "api",
    "jupyter==1.1.1",
    "pyright[nodejs]==1.1.400",
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "pytest-cov==6.1.1",
    "pytest-mock==3.14.0",
    "ruff==0.11.9",
    "test-utils",
    "transcriber",
]

[tool.uv.workspace]
members = ["api", "domain", "transcriber", "test_utils", "common", "scripts"]

[tool.uv.sources]
api = { workspace = true }
domain = { workspace = true }
transcriber = { workspace = true }
test-utils = { workspace = true }
common = { workspace = true }

[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # missing-trailing-comma
    "D100",   # undocumented-public-module
    "D101",   # undocumented-public-class
    "D102",   # undocumented-public-method
    "D103",   # undocumented-public-function
    "D104",   # undocumented-public-package
    "D105",   # undocumented-magic-method
    "D106",   # undocumented-public-nested-class
    "D107",   # undocumented-public-init
    "E501",   # line-too-long
    "ICN",    # flake8-import-conventions
    "S101",   # assert
    "TRY003", # raise-vanilla-args
]


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = ["unit: Unit tests", "integration: Integration tests"]

[tool.poe.tasks]
check-code.shell = "ruff check && ruff format --diff && pyright"
start-api-dev = "fastapi dev api/src/api/main.py"
start-api-pro.shell = "workers=$(nproc) && fastapi run --workers $workers api/src/api/main.py"
