name: Pull request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  continuous-integration:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      COMMON__ENVIRONMENT: Development
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: .python-version

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Unit tests
        run: uv run --frozen -- pytest -m unit
        shell: bash

      # - name: Integration tests
      #   run: uv run --frozen -- pytest -m integration
      #   shell: bash

  deploy-api-dev:
    needs: continuous-integration
    uses: ./.github/workflows/_deploy_api.yaml
    with:
      environment: dev
    secrets: inherit
