name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.25"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
