name: Pull request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  continuous-integration:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      python-archetype-docker-tag: ${{ steps.python-archetype-docker-tag.outputs.python-archetype-docker-tag }}
    env:
      COMMON__ENVIRONMENT: Development
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          version: 0.8.16

      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: .python-version

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Check code
        run: uv run --frozen -- poe check-code
        shell: bash

      - name: Unit tests
        run: uv run --frozen -- pytest -m unit
        shell: bash

      - name: Integration tests
        if: false
        run: uv run --frozen -- pytest -m integration
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Set docker tag
        id: python-archetype-docker-tag
        run: echo "python-archetype-docker-tag=myregistry/python-archetype:${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: src/python_archetype/api/Dockerfile
          tags: ${{ steps.python-archetype-docker-tag.outputs.python-archetype-docker-tag }}
          push: false

  deploy-dev:
    needs: continuous-integration
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment: dev
      docker_tag: ${{ needs.continuous-integration.outputs.python-archetype-docker-tag }}
    secrets: inherit

  deploy-stg:
    needs: [continuous-integration, deploy-dev]
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment: stg
      docker_tag: ${{ needs.continuous-integration.outputs.python-archetype-docker-tag }}
    secrets: inherit

  deploy-pro:
    needs: [continuous-integration, deploy-stg]
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment: pro
      docker_tag: ${{ needs.continuous-integration.outputs.python-archetype-docker-tag }}
    secrets: inherit
